### ISSUE TITLE
Parsing failure

### ISSUE THREAD

**Issue by Ayase-252** [Ayase-252/waife-crawler#1]
=========================

Parsing Error: Please report an issue in https://github.com/Ayase-252/waife-crawler/issues with following message.
URL: https://yande.re/post/show/385948

=========================
Traceback (most recent call last):
  File "/home/ayase-252/waife-crawler/crawler/yandere/yandere.py", line 111, in _parse_detail_page
    links = parse_detail_page(text)
  File "/home/ayase-252/waife-crawler/crawler/yandere/parser.py", line 59, in parse_detail_page
    raise RuntimeError('Page cannot be parsed: Parsing result is empty.')
RuntimeError: Page cannot be parsed: Parsing result is empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "waife-crawler.py", line 17, in <module>
    yandere_crawler.run()
  File "/home/ayase-252/waife-crawler/crawler/yandere/yandere.py", line 79, in run
    links = self._parse_detail_page(text, url)
  File "/home/ayase-252/waife-crawler/crawler/yandere/yandere.py", line 120, in _parse_detail_page
    raise RuntimeError('Parse Error: {}'.format(url))
RuntimeError: Parse Error: https://yande.re/post/show/385948

**Comment by Ayase-252** [comment]
Fixed in v0.1.1 #0d3b0b6
